### ISSUE TITLE
Filtering by traits in xUnit does not work as described in the docs

### ISSUE THREAD

**Issue by hiredgunhouse** [Microsoft/vstest-docs#83]
In the docs it says that with xUnit I should be able to do this:

`dotnet test --filter Category=bvt`

but it turns out that it doesn't work, I get following exception:

> "Exception filtering tests: No tests matched the filter because it contains one or more properties that are not valid (Category). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again."

**Comment by GZidar** [comment]
I had the same issue. The problem (for me at least) was that the test projects that reported the error did not actually have any tests in them. If you call the command from the solution folder and that solution file includes projects that are not test projects then any project file which has no tests in it will raise this error. To work around that issue I moved all my test projects to a sub-folder called tests and then created a solution that only contained the test projects so that I could run the dotnet test command from there without having to specify all the test projects individually.

**Comment by smadala** [comment]
@hiredgunhouse Are there any tests with `[Trait("Category", "bvt")]`? If yes, Can you share sample repro project? If no, There was https://github.com/Microsoft/vstest/issues/841 fixed related to this, Please update you Microsoft.NET.Test.Sdk package to latest version.

**Comment by hiredgunhouse** [comment]
@smadala I'll check that again and report.

**Comment by pvlakshm** [comment]
Validated that this works with the public 15.5 Preview 2 bits.
